/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.konobar;

import javax.swing.JCheckBox;
import util.ButtonEditorNarudzbinaDetalji;
import util.ButtonEditorObrisiNarudzbinu;
import util.ButtonRenderer;
import util.NarudzbinaModelTabeleKonobar;
import util.SingletonHolder;

/**
 *
 * @author Megi
 */
public class FNarudzbine extends javax.swing.JPanel {

    /**
     * Creates new form FNarudzbine
     */
    public FNarudzbine() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNarudzbine = new javax.swing.JTable();
        jbtnDodajNarudžbinu = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Narudžbine");

        jtblNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblNarudzbine);

        jbtnDodajNarudžbinu.setText("+ Dodaj narudžbinu");
        jbtnDodajNarudžbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajNarudžbinuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnDodajNarudžbinu)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDodajNarudžbinu)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajNarudžbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajNarudžbinuActionPerformed
        FNarudzbineDetalji fsn = new FNarudzbineDetalji();
        fsn.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_jbtnDodajNarudžbinuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajNarudžbinu;
    private javax.swing.JTable jtblNarudzbine;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jtblNarudzbine.setModel(new NarudzbinaModelTabeleKonobar(SingletonHolder.getInstance().getNarudzbine(SingletonHolder.getInstance().getUlogovaniKorisnik())));
        jtblNarudzbine.getColumn("Detalji").setCellRenderer(new ButtonRenderer());

        jtblNarudzbine.getColumn("Detalji").setCellEditor(new ButtonEditorNarudzbinaDetalji(new JCheckBox(),
                jtblNarudzbine));
        jtblNarudzbine.getColumn("Obriši").setCellRenderer(new ButtonRenderer());

        jtblNarudzbine.getColumn("Obriši").setCellEditor(new ButtonEditorObrisiNarudzbinu(new JCheckBox(),
                jtblNarudzbine));

    }
}
