/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.konobar;

import domen.Kategorija;
import domen.Potkategorija;
import domen.StavkaMenija;
import domen.StavkaNarudzbine;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import util.SingletonHolder;
import util.StavkeNarudzbineModelTabele;

/**
 *
 * @author Megi
 */
public class FStavkaNarudzbine extends javax.swing.JFrame {

    JTable jtblStavke;

    /**
     * Creates new form FStavkaNarudzbine
     */
    public FStavkaNarudzbine() {
        initComponents();
    }

    public FStavkaNarudzbine(JTable jtblStavke) {
        initComponents();
        this.jtblStavke = jtblStavke;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboKategorija = new javax.swing.JComboBox();
        comboPotkategorija = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnDodajStavku = new javax.swing.JButton();
        jbtnOdustani = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboStavkaMenija = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stavka narudžbine");

        comboKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hrana" }));
        comboKategorija.setToolTipText("");
        comboKategorija.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboKategorijaItemStateChanged(evt);
            }
        });

        comboPotkategorija.setToolTipText("");

        jLabel4.setText("Potkategorija");
        jLabel4.setToolTipText("");

        jLabel3.setText("Kategorija");
        jLabel3.setToolTipText("");

        jbtnDodajStavku.setText("Dodaj");
        jbtnDodajStavku.setToolTipText("");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jbtnOdustani.setText("Odustani");
        jbtnOdustani.setToolTipText("");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jLabel5.setText("Stavka menija");
        jLabel5.setToolTipText("");

        comboStavkaMenija.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(comboStavkaMenija, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPotkategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jbtnDodajStavku)
                    .addGap(46, 46, 46)
                    .addComponent(jbtnOdustani)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPotkategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStavkaMenija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnOdustani)
                        .addComponent(jbtnDodajStavku))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed
        StavkaNarudzbine sn = new StavkaNarudzbine();
        sn.setStavkaMenija((StavkaMenija) comboStavkaMenija.getSelectedItem());
        sn.setPlaceno(false);
        ((StavkeNarudzbineModelTabele) jtblStavke.getModel()).vratiListu().add(sn);

        this.dispose();
        jtblStavke.revalidate();
        jtblStavke.repaint();

    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void comboKategorijaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboKategorijaItemStateChanged
        List<Potkategorija> lista = new LinkedList<>();
        Kategorija k = (Kategorija) comboKategorija.getSelectedItem();
        for (Potkategorija pk : SingletonHolder.getInstance().getPotkategorije()) {
            if (pk.getKategorija().equals(k)) {
                lista.add(pk);
            }
        }
        comboPotkategorija.setModel(new DefaultComboBoxModel(lista.toArray()));
    }//GEN-LAST:event_comboKategorijaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FStavkaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FStavkaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FStavkaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FStavkaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FStavkaNarudzbine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboKategorija;
    private javax.swing.JComboBox comboPotkategorija;
    private javax.swing.JComboBox comboStavkaMenija;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnOdustani;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        comboKategorija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getKategorije().toArray()));

        comboPotkategorija.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                List<StavkaMenija> lista = new LinkedList<>();
                Potkategorija pk = (Potkategorija) comboPotkategorija.getSelectedItem();
                for (StavkaMenija sm : SingletonHolder.getInstance().getStavkeMenija()) {
                    if (sm.getPotkategorija().equals(pk)) {
                        lista.add(sm);
                    }
                }
                comboStavkaMenija.setModel(new DefaultComboBoxModel(lista.toArray()));
            }
        });
        //comboPotkategorija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getPotkategorije().toArray()));
        //comboStavkaMenija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getStavkeMenija().toArray()));
    }
}
