/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.admin;

import domen.Narudzbina;
import domen.StavkaMenija;
import domen.StavkaNarudzbine;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import util.ButtonEditorNarudzbinaDetalji;
import util.ButtonRenderer;
import util.NarudzbinaModelTabeleAdministrator;
import util.NarudzbinaModelTabeleKonobar;
import util.SingletonHolder;

/**
 *
 * @author Megi
 */
public class FNarudzbine extends javax.swing.JPanel {

    /**
     * Creates new form FKorisnici
     */
    public FNarudzbine() {
        initComponents();
        srediFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtDan = new javax.swing.JTextField();
        jtxtSto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtKonobar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnPronadji = new javax.swing.JButton();
        comboPotkategorija = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboKategorija = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboStavkaMenija = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblNarudzbine = new javax.swing.JTable();

        jLabel1.setText("Dan");

        jLabel2.setText("Sto");

        jLabel3.setText("Konobar");

        jbtnPronadji.setText("Pronađi");
        jbtnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPronadjiActionPerformed(evt);
            }
        });

        jLabel7.setText("Potkategorija");

        jLabel8.setText("Kategorija");

        jLabel9.setText("Stavka menija");

        jtblNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblNarudzbine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtDan, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtSto, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(comboPotkategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jbtnPronadji))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboStavkaMenija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtKonobar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPotkategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboStavkaMenija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jbtnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPronadjiActionPerformed
        List<Narudzbina> narudzbine = ((NarudzbinaModelTabeleAdministrator) jtblNarudzbine.getModel()).vratiListu();
        List<Narudzbina> narudzbinePretraga = new LinkedList<Narudzbina>();

        for (Narudzbina n : narudzbine) {
            if (!jtxtDan.getText().equals("")) {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm dd.MM.yyyy");
                if (sdf.format(n.getVreme()).contains(jtxtDan.getText())) {
                    narudzbinePretraga.add(n);
                }
            }
        }
        for (Narudzbina n1 : narudzbinePretraga) {
            if (!jtxtSto.getText().equals("")) {
                if (!n1.getSto().contains(jtxtSto.getText())) {
                    narudzbinePretraga.remove(n1);
                }
            }
        }
        for (Narudzbina n : narudzbinePretraga) {
            if (!jtxtSto.getText().equals("")) {
                if (!n.getSto().contains(jtxtSto.getText())) {
                    narudzbinePretraga.remove(n);
                }
            }
        }
        for (Narudzbina n : narudzbinePretraga) {
            if (!jtxtKonobar.getText().equals("")) {
                if (!n.getKonobar().getIme().contains(jtxtKonobar.getText())) {
                    narudzbinePretraga.remove(n);
                }
            }
        }

        for (Narudzbina n : narudzbinePretraga) {
            if (comboKategorija.getSelectedIndex() > -1) {
                for (StavkaNarudzbine sm : n.getStavke()) {
                    if (!sm.getStavkaMenija().getPotkategorija().getKategorija().equals(comboKategorija.getSelectedItem())) {
                        narudzbinePretraga.remove(n);
                    }
                }
            }

        }
        for (Narudzbina n : narudzbinePretraga) {
            if (comboPotkategorija.getSelectedIndex() > -1) {
                for (StavkaNarudzbine sm : n.getStavke()) {
                    if (!sm.getStavkaMenija().getPotkategorija().equals(comboPotkategorija.getSelectedItem())) {
                        narudzbinePretraga.remove(n);
                    }
                }
            }

        }
        for (Narudzbina n : narudzbinePretraga) {
            if (comboStavkaMenija.getSelectedIndex() > -1) {
                for (StavkaNarudzbine sm : n.getStavke()) {
                    if (!sm.equals(comboStavkaMenija.getSelectedItem())) {
                        narudzbinePretraga.remove(n);
                    }
                }
            }

        }

        jtblNarudzbine.setModel(new NarudzbinaModelTabeleAdministrator(narudzbinePretraga));
        jtblNarudzbine.revalidate();
    }//GEN-LAST:event_jbtnPronadjiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboKategorija;
    private javax.swing.JComboBox comboPotkategorija;
    private javax.swing.JComboBox comboStavkaMenija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPronadji;
    private javax.swing.JTable jtblNarudzbine;
    private javax.swing.JTextField jtxtDan;
    private javax.swing.JTextField jtxtKonobar;
    private javax.swing.JTextField jtxtSto;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jtblNarudzbine.setModel(new NarudzbinaModelTabeleAdministrator(SingletonHolder.getInstance().getNarudzbine(SingletonHolder.getInstance().getUlogovaniKorisnik())));
        jtblNarudzbine.getColumn("Detalji").setCellRenderer(new ButtonRenderer());

        jtblNarudzbine.getColumn("Detalji").setCellEditor(new ButtonEditorNarudzbinaDetalji(new JCheckBox(),
                jtblNarudzbine));
        comboKategorija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getKategorije().toArray()));
        comboPotkategorija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getPotkategorije().toArray()));
        comboStavkaMenija.setModel(new DefaultComboBoxModel(SingletonHolder.getInstance().getStavkeMenija().toArray()));

    }
}
