/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.admin;

import domen.Korisnik;
import java.util.List;
import javax.swing.JOptionPane;
import util.SingletonHolder;

/**
 *
 * @author Megi
 */
public class FUnosKorisnika extends javax.swing.JPanel {

    private String putanjaSlike;

    /**
     * Creates new form FUnosKorisnika
     */
    public FUnosKorisnika() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnPotvrdi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnDodaj = new javax.swing.JButton();
        jtxtLozinka = new javax.swing.JTextField();
        jtxtSlika = new javax.swing.JTextField();
        jtxtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtBrojTelefona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboTipKorisnika = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jtxtKorisnickoIme = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jlblGreskaKorisnickoIme = new javax.swing.JLabel();
        jlblGreskaIme = new javax.swing.JLabel();
        jlblGreskaLozinka = new javax.swing.JLabel();
        jlblGreskaPrezime = new javax.swing.JLabel();

        jbtnPotvrdi.setText("Potvrdi");
        jbtnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPotvrdiActionPerformed(evt);
            }
        });

        jLabel1.setText("Lozinka*");

        jbtnDodaj.setText("Dodaj...");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime*");

        jLabel3.setText("Prezime*");

        jLabel4.setText("Broj telefona");

        jLabel5.setText("E-mail");

        jLabel6.setText("Slika");

        jLabel7.setText("Tip korisnika*");

        comboTipKorisnika.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrator", "konobar", " " }));

        jLabel8.setText("Korisničko ime*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Unos novog korisnika");

        jlblGreskaKorisnickoIme.setForeground(new java.awt.Color(255, 0, 0));

        jlblGreskaIme.setForeground(new java.awt.Color(255, 0, 0));

        jlblGreskaLozinka.setForeground(new java.awt.Color(255, 0, 0));

        jlblGreskaPrezime.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtBrojTelefona)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtSlika)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDodaj))
                            .addComponent(jtxtEmail)
                            .addComponent(jtxtPrezime)
                            .addComponent(jtxtIme)
                            .addComponent(jtxtLozinka)
                            .addComponent(jtxtKorisnickoIme)
                            .addComponent(comboTipKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblGreskaKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblGreskaIme, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblGreskaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblGreskaPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel9))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jbtnPotvrdi))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jlblGreskaKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtLozinka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblGreskaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblGreskaIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlblGreskaPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTipKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jtxtSlika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnPotvrdi)
                .addGap(222, 222, 222))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        FIzborSlike fis = new FIzborSlike(null, this);
        fis.setVisible(true);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotvrdiActionPerformed

        if (jtxtKorisnickoIme.getText().equals("") || jtxtLozinka.getText().equals("") || jtxtIme.getText().equals("") || jtxtPrezime.getText().equals("") || comboTipKorisnika.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Morate popuniti obavezna polja", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            Korisnik k = new Korisnik();
            List<Korisnik> korisnici = SingletonHolder.getInstance().getKorisnici();
           boolean postoji=false;
            
            for (int i = 0; i < korisnici.size(); i++) {
                Korisnik k1 = korisnici.get(i);
                if (k1.getKorisnickoIme().equals(jtxtKorisnickoIme.getText())){
                postoji=true;
                break;
                }
            }
            if (!postoji){
             k.setKorisnickoIme(jtxtKorisnickoIme.getText());
            k.setKorisnickaSifra(jtxtLozinka.getText());
            k.setIme(jtxtIme.getText());
            k.setPrezime(jtxtPrezime.getText());
            k.setPrezime(jtxtPrezime.getText());
            k.setTipKorisnika((String) comboTipKorisnika.getSelectedItem());
            k.setTelefon(jtxtBrojTelefona.getText());
            k.setSlika(jtxtSlika.getText());
            k.setEmail(jtxtEmail.getText());

            korisnici.add(k);
            }
            else {
                  JOptionPane.showMessageDialog(this, "Korisničko ime već postoji!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
        JOptionPane.showMessageDialog(this, "Uspešno ste dodali korisnika!", "Unos korisnika", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnPotvrdiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboTipKorisnika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnPotvrdi;
    private javax.swing.JLabel jlblGreskaIme;
    private javax.swing.JLabel jlblGreskaKorisnickoIme;
    private javax.swing.JLabel jlblGreskaLozinka;
    private javax.swing.JLabel jlblGreskaPrezime;
    private javax.swing.JTextField jtxtBrojTelefona;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtKorisnickoIme;
    private javax.swing.JTextField jtxtLozinka;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtSlika;
    // End of variables declaration//GEN-END:variables

    public String getPutanjaSlike() {
        return putanjaSlike;
    }

    public void setPutanjaSlike(String putanjaSlike) {
        this.putanjaSlike = putanjaSlike;
        jtxtSlika.setText(putanjaSlike);
    }
}
